# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SellerRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nombres: str=None, apellidos: str=None, correo: str=None, celular: str=None, estado: int=None):  # noqa: E501
        """SellerRequest - a model defined in Swagger

        :param nombres: The nombres of this SellerRequest.  # noqa: E501
        :type nombres: str
        :param apellidos: The apellidos of this SellerRequest.  # noqa: E501
        :type apellidos: str
        :param correo: The correo of this SellerRequest.  # noqa: E501
        :type correo: str
        :param celular: The celular of this SellerRequest.  # noqa: E501
        :type celular: str
        :param estado: The estado of this SellerRequest.  # noqa: E501
        :type estado: int
        """
        self.swagger_types = {
            'nombres': str,
            'apellidos': str,
            'correo': str,
            'celular': str,
            'estado': int
        }

        self.attribute_map = {
            'nombres': 'nombres',
            'apellidos': 'apellidos',
            'correo': 'correo',
            'celular': 'celular',
            'estado': 'estado'
        }
        self._nombres = nombres
        self._apellidos = apellidos
        self._correo = correo
        self._celular = celular
        self._estado = estado

    @classmethod
    def from_dict(cls, dikt) -> 'SellerRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SellerRequest of this SellerRequest.  # noqa: E501
        :rtype: SellerRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nombres(self) -> str:
        """Gets the nombres of this SellerRequest.


        :return: The nombres of this SellerRequest.
        :rtype: str
        """
        return self._nombres

    @nombres.setter
    def nombres(self, nombres: str):
        """Sets the nombres of this SellerRequest.


        :param nombres: The nombres of this SellerRequest.
        :type nombres: str
        """

        self._nombres = nombres

    @property
    def apellidos(self) -> str:
        """Gets the apellidos of this SellerRequest.


        :return: The apellidos of this SellerRequest.
        :rtype: str
        """
        return self._apellidos

    @apellidos.setter
    def apellidos(self, apellidos: str):
        """Sets the apellidos of this SellerRequest.


        :param apellidos: The apellidos of this SellerRequest.
        :type apellidos: str
        """

        self._apellidos = apellidos

    @property
    def correo(self) -> str:
        """Gets the correo of this SellerRequest.


        :return: The correo of this SellerRequest.
        :rtype: str
        """
        return self._correo

    @correo.setter
    def correo(self, correo: str):
        """Sets the correo of this SellerRequest.


        :param correo: The correo of this SellerRequest.
        :type correo: str
        """

        self._correo = correo

    @property
    def celular(self) -> str:
        """Gets the celular of this SellerRequest.


        :return: The celular of this SellerRequest.
        :rtype: str
        """
        return self._celular

    @celular.setter
    def celular(self, celular: str):
        """Sets the celular of this SellerRequest.


        :param celular: The celular of this SellerRequest.
        :type celular: str
        """

        self._celular = celular

    @property
    def estado(self) -> int:
        """Gets the estado of this SellerRequest.


        :return: The estado of this SellerRequest.
        :rtype: int
        """
        return self._estado

    @estado.setter
    def estado(self, estado: int):
        """Sets the estado of this SellerRequest.


        :param estado: The estado of this SellerRequest.
        :type estado: int
        """

        self._estado = estado
